describe("actiomns", ()=>{
    it("sample1", async function(){
        browser.url("https://www.selenium.dev/selenium/docs/api/java/index.html?overview-summary.html")
        browser.maximizeWindow()
        await browser.pause(1000)
        await browser.switchToFrame(0)
        await $("=org.openqa.selenium").click()
        await browser.switchToFrame(null)
        //await browser.switchToParentFrame()
        await browser.pause(1000)
        await browser.switchToFrame(await $('//iframe[@name="packageFrame"]'))
        await $("=Alert").click()
        await browser.switchToFrame(null)
        await browser.pause(1000)
        await browser.switchToFrame(await $('//iframe[@name="classFrame"]'))
        await $("=accept").click()
        await browser.pause(2000)
    })
})